(function(global){
  'use strict';
  const FIELDS={machine:'기계번호',model:'모델명',customer_id:'고객번호',company:'고객사명',name:'이름',phone:'전화',email:'이메일',region:'지역',address:'현재 주소',position:'직급',updated:'정보수정일',last_name:'성',first_name:'이름',mobile:'휴대폰'};
  const DEFAULT_KEYWORDS=['총무','인사','경영지원','구매'];
  const SECONDARY_TITLES=['대표','사장','실장','팀장'];
  const clean=v=>v==null?'':String(v).trim();
  const strip=v=>clean(v).replace(/\s/g,'');
  function combineName(row){const a=clean(row.last_name),b=clean(row.first_name);const parts=[a,b].filter(Boolean);const hangul=p=>/^[가-힣]+$/.test(p||'');return parts.join(parts.length===2&&hangul(a)&&hangul(b)?'':' ');}
  function parseDate(value){const v=clean(value);if(!v)return null;let m=v.match(/^(\d{4})[-/.]?(\d{2})[-/.]?(\d{2})(?:[ T](\d{2}):(\d{2})(?::(\d{2}))?)?$/);if(!m)return null;const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]),Number(m[4]||0),Number(m[5]||0),Number(m[6]||0));if(d.getFullYear()!=Number(m[1])||d.getMonth()!=Number(m[2])-1||d.getDate()!=Number(m[3])||d>new Date())return null;return d;}
  function addressMatches(row,keywords){const a=strip(row.address);return keywords.some(k=>strip(k)&&a.includes(strip(k)));}
  function titleRank(row){const t=strip(row.position);if(t==='대표'||t==='대표이사')return 0;if(t==='사장')return 1;if(t.endsWith('실장')&&!t.endsWith('부실장'))return 2;if(t.endsWith('팀장')&&!t.endsWith('부팀장'))return 3;return 4;}
  function contactErrors(row,required=['machine','model','customer_id','company','name','phone','email','region']){const errors=[];required.forEach(k=>{if(k==='phone')return;if(!clean(row[k]))errors.push(FIELDS[k]+' 누락');});if(required.includes('phone')&&!clean(row.phone)&&!clean(row.mobile))errors.push('전화·휴대폰 모두 누락');if(clean(row.last_name)||clean(row.first_name)){if(!clean(row.last_name))errors.push('성 누락');if(!clean(row.first_name))errors.push('이름 누락');}const email=clean(row.email);if(email&&!/^\S+@\S+\.\S+$/.test(email))errors.push('이메일 형식 확인');for(const k of ['phone','mobile']){const p=clean(row[k]);if(p&&(!/\d/.test(p)||!(/^[\d\s+().\-#/내선extEXT:]+$/.test(p))))errors.push(FIELDS[k]+' 형식 확인');}return errors;}
  function priority(row,keywords){if(addressMatches(row,keywords))return 1;if(titleRank(row)<4&&!contactErrors(row,['name','phone','email']).length)return 2;return 3;}
  function order(row,keywords){const p=priority(row,keywords);return [p,p===2?titleRank(row):0];}
  function latestValue(rows,key,reasons){const present=rows.filter(r=>clean(r[key]));if(!present.length)return '';const dated=present.filter(r=>r._date);const chosen=(dated.length?dated:present).reduce((a,b)=>(!a||((b._date&&a._date)&&b._date>a._date))?b:a,null);const peers=present.filter(r=>((r._date&&chosen._date&&r._date.getTime()===chosen._date.getTime())||!r._date));if(peers.some(r=>r[key]!==chosen[key]))reasons.push(FIELDS[key]+' 충돌: 같은 날짜 또는 날짜 없는 다른 값');return chosen[key];}
  function buildResult(records,keywords,excludedTargets){
    const keys=(keywords==null?DEFAULT_KEYWORDS:keywords).map(clean).filter(Boolean);const targets=excludedTargets||[];const exReasons={};targets.forEach(r=>{const id=clean(r.customer_id);if(id)exReasons[id]=clean(r.reason);});const groups=new Map(),rejected=[],normalized=[];
    (records||[]).forEach((orig,index)=>{const r={};Object.keys(FIELDS).forEach(k=>r[k]=clean(orig[k]));if(r.last_name||r.first_name)r.name=combineName(r);r.source=clean(orig.source);r.warnings=Array.isArray(orig.warnings)?orig.warnings.slice():[];r._date=parseDate(r.updated);r.record_id=index;normalized.push(r);if(!r.customer_id)rejected.push({...r,reason:'고객번호 누락: 자동 연결 불가'});else{if(!groups.has(r.customer_id))groups.set(r.customer_id,[]);groups.get(r.customer_id).push(r);}});
    const customers=[],machines=[];
    for(const [id,rows] of groups){const reasons=[];rows.forEach(r=>{reasons.push(...r.warnings);if(r.updated&&!r._date)reasons.push('날짜 형식 오류 또는 미래 날짜');});const customer={};Object.keys(FIELDS).forEach(k=>customer[k]='');customer.customer_id=id;customer.company=latestValue(rows,'company',reasons);customer.region=latestValue(rows,'region',reasons);const byMachine=new Map();rows.forEach(r=>{if(r.machine){if(!byMachine.has(r.machine))byMachine.set(r.machine,[]);byMachine.get(r.machine).push(r);}});const ids=[],models=[];for(const [mid,entries] of [...byMachine.entries()].sort()){const model=latestValue(entries,'model',reasons);ids.push(mid);models.push(model||'(모델 미확인)');if(!model)reasons.push(mid+' 모델명 누락');machines.push({customer_id:id,company:customer.company,machine:mid,model,source:[...new Set(entries.map(r=>r.source).filter(Boolean))].join('\n')});}customer.machine=ids.join('\n');customer.model=models.join('\n');
      const byPerson=new Map();rows.forEach(r=>{if(!['name','phone','mobile','email','position'].some(k=>r[k]))return;const key=r.name||('unknown-'+r.record_id);if(!byPerson.has(key))byPerson.set(key,[]);byPerson.get(key).push(r);});let current=[];for(const entries of byPerson.values()){const dates=entries.filter(r=>r._date).map(r=>r._date);const newest=dates.length?new Date(Math.max(...dates.map(d=>d.getTime()))):null;current.push(...entries.filter(r=>!r._date||(newest&&r._date.getTime()===newest.getTime())));}const candidates=current.filter(r=>priority(r,keys)<3);if(!candidates.length)reasons.push('1순위 주소 키워드 또는 연락처가 완비된 2순위 직급 후보 없음');const display=candidates.length?candidates:current.length?current:rows;const best=display.map(r=>order(r,keys)).sort((a,b)=>a[0]-b[0]||a[1]-b[1])[0];const preferred=display.filter(r=>{const o=order(r,keys);return o[0]===best[0]&&o[1]===best[1]});const chosen=preferred.reduce((a,b)=>(!a||((b._date&&a._date)&&b._date>a._date))?b:a,null);const p=priority(chosen,keys);if(preferred.some(r=>!r._date))reasons.push('담당자 정보 날짜 없음 또는 확인 불가');for(const k of ['name','last_name','first_name','phone','mobile','email','address','position','updated'])customer[k]=chosen[k];reasons.push(...contactErrors(customer));customer.status=reasons.length?'확인 필요':'설문 대상';customer.reasons=[...new Set(reasons)];customer.source=chosen.source;customer.all_sources=[...new Set(rows.map(r=>r.source).filter(Boolean))].join('\n');customer.priority=p;customer.selection=(p===1?'1순위: 현재 주소에 부서 키워드 포함':p===2?`2순위: ${SECONDARY_TITLES[titleRank(chosen)]||'직급'} / 이름·연락처·이메일 완비`:'구매 담당자 확인 필요')+' / 동일 순위 최신 행 선택';customer.manual=false;customer.candidates=rows.map(r=>{const c={...r};delete c._date;return c;});if(exReasons[id]!==undefined){customer.status='설문 제외';customer.reasons=[...new Set([...customer.reasons,exReasons[id]||'제외 목록에 포함'])];}customers.push(customer);}
    const ownership=new Map();machines.forEach(m=>{if(!ownership.has(m.machine))ownership.set(m.machine,new Set());ownership.get(m.machine).add(m.customer_id);});customers.forEach(c=>{if(c.machine.split('\n').some(m=>m&&ownership.get(m)?.size>1)){c.reasons.push('동일 기계번호가 여러 고객번호에 존재');c.status='확인 필요';}});customers.sort((a,b)=>a.priority-b.priority);return {customers,machines,records:normalized.map(r=>{const c={...r};delete c._date;return c;}),rejected:rejected.map(r=>{const c={...r};delete c._date;return c;}),keywords:keys,excluded_ids:Object.keys(exReasons).sort()};
  }
  function approveCustomer(result,customerId,values){const c=result.customers.find(x=>x.customer_id===customerId);if(!c)throw new Error('고객을 찾을 수 없습니다.');const updated={...c};['company','name','phone','mobile','email','region','address','position'].forEach(k=>{if(values[k]!==undefined)updated[k]=clean(values[k]);});if('last_name' in values||'first_name' in values){updated.last_name=clean(values.last_name);updated.first_name=clean(values.first_name);updated.name=combineName(updated);}const errors=contactErrors(updated);if(updated.model.includes('(모델 미확인)'))errors.push('모델명 누락: 원본 수정 후 다시 불러오세요.');if(errors.length)throw new Error(errors.join(' / '));updated.status='설문 대상';updated.manual=true;updated.reasons=[];updated.priority=addressMatches(updated,result.keywords)?1:2;updated.selection='사용자 확인: 담당자 직급 및 최신 정보 확인';updated.confirmed_at=new Date().toISOString().slice(0,19);Object.assign(c,updated);result.customers.sort((a,b)=>a.priority-b.priority);return c;}
  global.CustomerCore={buildResult,approveCustomer,contactErrors,parseDate}; if(typeof module!=='undefined')module.exports=global.CustomerCore;
})(typeof globalThis!=='undefined'?globalThis:window);
